secret:
  elasticsearch:
    rest-client:
      apikey: ${ELASTICSEARCH_API_KEY}
  riot:
    apikey: ${RIOT_API_KEY}

spring:
  application:
    name: troll-inspector
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/teemo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE