spring:
  application:
    name: troll-inspector
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/teemo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234