spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        auto_quote_keyword: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

crawling-v1:
  remote-ip: http://${REMOTE_IP}:${REMOTE_PORT}

crawling-v2:
  remote-ip: http://${REMOTE_IP2}:${REMOTE_PORT2}