spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        auto_quote_keyword: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect

crawling:
  url: https://www.op.gg/leaderboards/tier?page=
  remote-ip: http://${REMOTE_IP}:${REMOTE_PORT}