spring:
  datasource:
    url: jdbc:mysql://${DB_IP}:${DB_PORT}/myDB?rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${USER_NAME}
    password: ${PASSWORD}
    hikari:
      maximum-pool-size: 50
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        auto_quote_keyword: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

crawling-v1:
  url: https://www.op.gg/leaderboards/tier?page=
  remote-ip: http://${REMOTE_IP}:${REMOTE_PORT}

crawling-v2:
  url: https://www.op.gg/leaderboards/tier?page=
  remote-ip: http://${REMOTE_IP2}:${REMOTE_PORT2}